WIP #122 support CQL comments
schemasafe/troy pull request #139
Opened 2017-01-04 12:06 UTC by Eman-Shaaban

#122

2017-01-09 12:12 UTC, tabdulradi requested changes

2017-01-09 12:12 UTC, tabdulradi commented on cql-parser/src/main/scala/troy/cql/parser/CqlParser.scala
> +    parse(phrase(dmlDefinition <~ semicolon.? <~ comment.?), input)
Comments wont't be supported inside queries. Instead they should be supported inside schema.cql file only.

2017-01-09 12:12 UTC, tabdulradi commented on cql-parser/src/main/scala/troy/cql/parser/CqlParser.scala
> +    def str = "[0-9a-fA-F]".r
I am sure we have this regex defined somewhere else we can reuse

2017-01-09 12:12 UTC, tabdulradi commented on cql-parser/src/main/scala/troy/cql/parser/CqlParser.scala
> +    def multi = s"/*$str*/".r ^^ MultiLine
This won't work, the regex won't allow new lines.
Maybe write a test case first

2017-01-21 18:22 UTC, tabdulradi commented on cql-parser/src/main/scala/troy/cql/parser/CqlParser.scala
> +  def comment = ident+
Is this line used?

2017-01-21 18:27 UTC, tabdulradi commented on cql-parser/src/main/scala/troy/cql/parser/CqlParser.scala
> +  // Comments Parser
This comment can be something line "Ignores comments"

2017-01-21 23:07 UTC, tabdulradi commented on cql-parser/src/test/scala/troy/cql/parser/ddl/CreateTableParserTest.scala
> +          user_trans_id bigint
What about adding test for comments similar to those?

2017-01-21 23:33 UTC, Eman-Shaaban commented on cql-parser/src/test/scala/troy/cql/parser/ddl/CreateTableParserTest.scala
> +          user_trans_id bigint
in the same file CreateTableParserTest.scala ??

2017-02-01 21:35 UTC, tabdulradi approved these changes

2017-02-01 21:36 UTC, merged